### ISSUE TITLE
incompatible with PhpStorm 2023.2

### ISSUE THREAD

**Issue by atli-c** [cego/gitlab-ci-local-intellij-plugin#17]
My PhpStorm says:

> Incompatible: requires IDE build 231.* or earlier

Gitlab-CI-Local Helper plugin version 0.0.4  
PhpStorm 2023.2: "Build #PS-232.8660.205, built on July 28, 2023" (on macOS)

**Comment by LauJosefsen** [comment]
Closed by #19
